# Generated by Django 4.2.4 on 2023-08-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(error_messages={'blank': 'This field must not be empty', 'max_length': 'This field must not be more than 254 characters', 'null': 'This field must not be empty', 'unique': 'This email already exists'}, max_length=254, unique=True)),
                ('fullname', models.CharField(max_length=300)),
                ('mobile', models.CharField(error_messages={'blank': 'This field must not be empty', 'max_length': 'This field must not be more than 11 characters', 'null': 'This field must not be empty', 'unique': 'This Phone Number already exists'}, max_length=11, unique=True)),
                ('account_number', models.CharField(default='1234567890', error_messages={'blank': 'This field must not be empty', 'max_length': 'This field must not be more than 10 characters', 'null': 'This field must not be empty', 'unique': 'This Account Number already exists'}, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'User',
                'ordering': ('-created_at',),
            },
        ),
    ]
