# Generated by Django 4.2.4 on 2023-08-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.CharField(error_messages={'blank': 'This field must not be empty', 'max_length': 'This field must not be more than 10 characters', 'null': 'This field must not be empty', 'unique': 'This Account Number already exists'}, max_length=10, unique=True),
        ),
    ]
